default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: lostandfound
  password: lostandfound

development:
  <<: *default
  database: lostandfound_dev

test:
  <<: *default
  database: lostandfound_test
