# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af845571b6b05eb815ccdbddae1d78041e1644f85ad0a031017c892db9d34bbee9ea764e550646b0e5422bf15ba3a4a777795a558d003a6588ad47c69e556e01

test:
  secret_key_base: c89736f043e8108a0cd1f60fae853d20923837153e3f0fd10d3331f5301407e3caffa393a4827159a2992517362afad862bd57cfe10e4c43d44100a2fdb648df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
